### ISSUE TITLE
Tests in the tests/interop folder are not being run

### ISSUE THREAD

**Issue by igorT** [hjdivad/ember-m3#786]
None of the tests in https://github.com/hjdivad/ember-m3/tree/master/tests/interop seem to be running right now, probably because the interop folder is not being picked up. I am not yet clear on whether this broke at some point, or never worked :(

**Comment by runspired** [comment]
These tests are only run in CI by default (or whenever the full `ember-data` package is present) since they depend on the full experience vs the stripped down experience. You can see recent test output with them in it here: https://github.com/hjdivad/ember-m3/pull/784/checks?check_run_id=809809517

This is determined at build time here: https://github.com/hjdivad/ember-m3/blob/master/ember-cli-build.js#L26-L30
